#include <exec/types.h>

#define MENU_UEBER 100
#define MENU_UMGEBUNG 101
#define MENU_FENSTERFIX 102
#define MENU_ENDE 103
#define MENU_NEU 200
#define MENU_LADEN 201
#define MENU_SPEICHERN 202
#define MENU_SPEICHERNALS 203
#define MENU_SPEICHERNALSAUTOLOAD 204
#define MENU_IMPORTSMF 205
#define MENU_EXPORTSMF 206
#define MENU_PROJEINST 207
#define MENU_SYSEX 208
#define MENU_MISCHPULT 209
#define MENU_CTRLCHANGE 210
#define MENU_PROGSENDEN 211
#define MENU_SYSEXSENDEN 212
#define MENU_MIXSENDEN 213
#define MENU_ALLOFFSENDEN 214
#define MENU_EDIT_UNDO 300
#define MENU_EDIT_REDO 301
#define MENU_SEQ_COPY 400
#define MENU_SEQ_PASTE 401
#define MENU_SEQ_LOESCHEN 402
#define MENU_SEQ_QUANT 403
#define MENU_SEQ_SCHNEIDEN 404
#define MENU_SEQ_VERBINDEN 405
#define MENU_SEQ_ALIASREAL 406
#define MENU_SEQ_UNTERTEILEN 407
#define MENU_SEQ_MARK_ALLELIED 408
#define MENU_SEQ_MARK_ALLESPUR 409
#define MENU_SEQ_MARK_EDITPOS 410
#define MENU_SEQ_SETZELOOP 411
#define MENU_SPR_LOESCHEN 500
#define MENU_SPR_MUTEN 501
#define MENU_SPR_HINZU 502
#define MENU_SPR_DUPLIZIEREN 503
#define MENU_SPR_SOLO 504
#define MENU_SPR_MUTESAUS 505
#define MENU_SPR_AUTO_VOL 506
#define MENU_SPR_AUTO_PAN 507
#define MENU_SPR_AUTO_CTRL1 508
#define MENU_SPR_AUTO_CTRL2 509
#define MENU_SPR_AUTO_CTRL3 510
#define MENU_SPR_AUTO_CTRL4 511
#define MENU_SPR_AUTO_CTRL5 512
#define MENU_SPR_AUTO_CTRL6 513
#define MENU_SPR_AUTO_HIDE 514
#define MENU_SPR_AUTO_DEL 515
#define MENU_SPR_AUTO_COPY 516
#define MENU_SPR_AUTO_PASTE 517
#define MENU_SPR_AUTO_A2C 518
#define MENU_SPR_AUTO_C2A 519


#define MENU_EV_LOESCHEN 600
#define MENU_EV_QUANT_ON 601
#define MENU_EV_QUANT_OFF 602
#define MENU_EV_QUANT_ONNEAR 603
#define MENU_EV_DYNAMIK 604
#define MENU_EV_MARK_ALLE 605
#define MENU_EV_MARK_HOEHERE 606
#define MENU_EV_MARK_TIEFERE 607
#define MENU_EV_MARK_ANSCHLAEGE 608
#define MENU_EV_MARK_KANAL 609
#define MENU_EV_REPARIEREN 610

#define MENU_EV_CONTRHINZU 700
#define MENU_EV_MARK_NICHTS 701
#define MENU_EV_REDUZIEREN 702
#define MENU_EV_GLAETTEN 703

void ErstelleMenuLibs(void);
void EntferneMenuLibs(void);
void ErstelleMenu(void);
void EntferneMenu(void);
ULONG MenuPunkt(ULONG code);
void MenuDeaktivieren(BYTE typ, BYTE num, BOOL status);
void MenuItemDeaktivieren(BYTE typ, UWORD code, BOOL status);
ULONG EdMenuPunkt(ULONG code);
ULONG MinMenuPunkt(ULONG code);
