#include <exec/types.h>

struct SEQUENZ *ErstelleSequenz(WORD s, LONG t, BOOL allocevents);
BOOL AddEvbl(struct EVENTBLOCK *evbl);
void EvblsAbschneiden(struct EVENTBLOCK *evbl);
struct SEQUENZ *NeueSequenzEinordnen(WORD s);
void SequenzEntfernen(struct SEQUENZ *seq);
void SpurSequenzenEntfernen(WORD s);
void SequenzAusSpurEntfernen(struct SEQUENZ *seq);
struct SEQUENZ *TaktSequenz(WORD s, LONG t, BYTE *p);
BOOL HoleMarkSequenzenRahmen(LONG *start, LONG *ende);
void MarkSequenzenVerschiebenTest(WORD *sd, LONG *d);
void MarkSequenzenVerschieben(WORD s, WORD sd, LONG d);
void MarkSequenzenEntfernen(void);
struct SEQUENZ *NeuesAlias(struct SEQUENZ *original);
struct SEQUENZ *MarkSequenzenAlias(void);
struct SEQUENZ *NeueKopie(struct SEQUENZ *original);
struct SEQUENZ *MarkSequenzenKopieren(void);
void MarkSequenzenAliasZuReal(void);
void SequenzenInSpurMarkieren(WORD s);
void SequenzenAbXMarkieren(LONG t);
void NichtsMarkieren(void);
void BereichMarkieren(WORD vs, WORD bs, LONG vt, LONG bt);
void SequenzenSpuren(WORD s);
void MarkSequenzenZerschneiden(LONG tp);
void SequenzUnterteilen(struct SEQUENZ *seq, LONG tp);
void MarkSequenzenVerbinden(void);
void MarkSequenzenStartVerschieben(WORD d);
void MarkSequenzenEndeVerschieben(WORD d);
void AlleAliaseZuweisen(void);
void InitSequenzInfo(void);
void MarkSequenzInfo(void);
void MarkSequenzenSetzeName(STRPTR name);
void MarkSequenzenSetzeTrans(BYTE trans);
void MarkSequenzenSetzeMute(BOOL mute);
