#include <exec/types.h>

struct SEQUENZ *ErstelleSequenz(int16 s, int32 t, BOOL allocevents);
BOOL AddEvbl(struct EVENTBLOCK *evbl);
void EvblsAbschneiden(struct EVENTBLOCK *evbl);
struct SEQUENZ *NeueSequenzEinordnen(int16 s);
void SequenzEntfernen(struct SEQUENZ *seq);
void SpurSequenzenEntfernen(int16 s);
void SequenzAusSpurEntfernen(struct SEQUENZ *seq);
struct SEQUENZ *TaktSequenz(int16 s, int32 t, int8 *p);
BOOL HoleMarkSequenzenRahmen(int32 *start, int32 *ende);
void MarkSequenzenVerschiebenTest(int16 *sd, int32 *d);
void MarkSequenzenVerschieben(int16 s, int16 sd, int32 d);
void MarkSequenzenEntfernen(void);
struct SEQUENZ *NeuesAlias(struct SEQUENZ *original);
struct SEQUENZ *MarkSequenzenAlias(void);
struct SEQUENZ *NeueKopie(struct SEQUENZ *original);
struct SEQUENZ *MarkSequenzenKopieren(void);
void MarkSequenzenAliasZuReal(void);
void SequenzenInSpurMarkieren(int16 s);
void SequenzenAbXMarkieren(int32 t);
void NichtsMarkieren(void);
void BereichMarkieren(int16 vs, int16 bs, int32 vt, int32 bt);
void SequenzenSpuren(int16 s);
void MarkSequenzenZerschneiden(int32 tp);
void SequenzUnterteilen(struct SEQUENZ *seq, int32 tp);
void MarkSequenzenVerbinden(void);
void MarkSequenzenStartVerschieben(int16 d);
void MarkSequenzenEndeVerschieben(int16 d);
void AlleAliaseZuweisen(void);
void InitSequenzInfo(void);
void MarkSequenzInfo(void);
void MarkSequenzenSetzeName(STRPTR name);
void MarkSequenzenSetzeTrans(int8 trans);
void MarkSequenzenSetzeMute(BOOL mute);
